#!/bin/bash

docker run \
  -it \
  --privileged \
  -w /root/ros2_ws \
  --env AUDIODEV=default:Device \
  --name car \
  --group-add audio \
  --volume=/dev:/dev:rw \
  --volume /dev/bus/usb:/dev/bus/usb \
  --device-cgroup-rule='c 189:* rmw' \
  --network host \
  --device /dev/ps3-joystick \
  --device /dev/input/js0 \
  --device /dev/roboclaw \
  --device /dev/oak-d \
  --device /dev/lidar \
  --restart unless-stopped \
  -e SHELL=/bin/bash \
  -v ~/red-crash:/root/ros2_ws \
  -v ~/red-crash/noetic/ws:/root/ws \
  brianerickson/ros2-jazzy /bin/bash