#!/bin/bash

docker run \
  -it \
  --privileged \
  --rm \
  -w /root/ws \
  --env AUDIODEV=front:Device \
  --name car \
  --group-add audio \
  --volume=/dev:/dev:rw \
  --device-cgroup-rule='c 189:* rmw' \
  --network host \
  --device /dev/ps3-joystick \
  --device /dev/input/js0 \
  --device /dev/roboclaw \
  --device /dev/oak-d \
  --device /dev/lidar \
  -e SHELL=/bin/bash \
  -v ~/red-crash/ws:/root/ws \
  brianerickson/ros /bin/bash -c "screen -c launch_all.screenrc;exit"
